<?php
/**
 * @file create.php - create a new database and a new db_connect_params.php file
 * @author Erel Segal
 * @date 2007-09-25
 */
error_reporting(E_ALL);
set_time_limit(0);

print "<h1>Create a new database for textia</h1>\n";
print "<h2>Requirements</h2>
<ul>
	<li>MySQL 5+
	<li>PHP 5+
	<li>and PHP-MySQL extension</li>
</ul>
";

$SCRIPT = dirname(__FILE__) . '/../../script';
	
require_once("$SCRIPT/sql.php");
require_once("$SCRIPT/sql_backup.php");
require_once("$SCRIPT/coalesce.php");
require_once('tables.php');

if (count($_POST)>0) {
	update_create_page();
} else {
	show_create_page();
}

function show_create_page() {
	@include_once("db_root_params.php"); // only if it exists
	set_coalesce($GLOBALS['db_host'],'localhost');
	set_coalesce($GLOBALS['root_username'],coalesce($GLOBALS['db_user'],'root'));
	set_coalesce($GLOBALS['root_password'],coalesce($GLOBALS['db_pass'],''));

	@include_once("db_connect_params.php"); // only if it exists
	set_coalesce($GLOBALS['db_name'],'');
	set_coalesce($GLOBALS['db_user'],'');
	set_coalesce($GLOBALS['db_pass'],'');

	print "
	<form method='post'>
		<h2>Credentials</h2>
		<p>Database host: <input name='db_host' value='$GLOBALS[db_host]' />
		<p>MySQL root username: <input name='root_username' value='$GLOBALS[root_username]' />
		<p>MySQL root password: <input type='password' name='root_password' value='' />

		<h2>New database data</h2>
		<p>New database name: <input name='db_name' value='$GLOBALS[db_name]' />
		<p>New user name: <input name='db_user' value='$GLOBALS[db_user]' />
		<p>New user password: <input type='password' name='db_pass' value='$GLOBALS[db_pass]' />
		<p><input type='checkbox' name='drop_db' />Drop existing database
		<p><input type='submit' name='submit' />
	</form>
	";
}

function update_create_page() {
	@include_once("db_connect_params.php"); // only if it exists

	print "<h2>New database creation</h2>";
	print "<p>create_database_and_user();";
	create_database_and_user();
	print "<p>create_db_connect_params();";
	create_db_connect_params();
	print "<p>require('db_connect.php');";
	require('db_connect.php');
	if ($GLOBALS['db_created']) {
		print "<p>create_database_tables();";
		create_database_tables();
	}
	print "<p>create complete!</p>\n";
	
	print "<h2>Additional Tasks</h2>
	<ol>
	 <li>Make the script 'admin/soldiers_forget_loyalty.php' a weekly cron job.</li>
	 <li>Go to <a href='../index.php'>the index page</a> to start playing!</li>
	</ol>
	"; 
}


function create_database_and_user() {
	$link = sql_connect(
		$_POST['db_host'],
		$_POST['root_username'],
		$_POST['root_password']);

	if (!$link)
		die('Could not connect as root: ' . sql_get_last_message());

	if (isset($_POST['drop_db']))
		sql_query_or_die("DROP DATABASE IF EXISTS $_POST[db_name]");

	if (sql_database_exists($_POST['db_name'])) {
		echo "<p>Database $_POST[db_name] already exists - won't create it</p>\n";
		$GLOBALS['db_created'] = false;
	} 	else {
		echo "<p>Creating database $_POST[db_name]</p>\n";
		sql_query_or_die("
			CREATE DATABASE $_POST[db_name] 
			CHARACTER SET utf8");
		sql_query_or_die("SET storage_engine=MYISAM"); // TODO: test it!
		$GLOBALS['db_created'] = true;
	}

	$db_user_quoted = quote_smart($_POST['db_user'])."@".quote_smart($_POST['db_host']);
	sql_query_or_die("GRANT ALL PRIVILEGES ON $_POST[db_name].* 
		TO $db_user_quoted IDENTIFIED BY ".quote_all($_POST['db_pass'])." WITH GRANT OPTION");
	sql_query_or_die("GRANT RELOAD ON *.* 
		TO $db_user_quoted");

	/* Old version: */ 
	$socket_query = sql_query_or_die("SHOW VARIABLES LIKE 'socket'");
    $_POST['db_sock'] = sql_result($socket_query,0,1);

	sql_close($link); // root logs out
}

function create_db_connect_params() {
	file_put_contents(dirname(__FILE__)."/db_connect_params.php", "<?php 
/**
 * @file parameters for db_connect.php and config.php
 * Automatically generated by $_SERVER[PHP_SELF] at $GLOBALS[current_time]
 */

\$GLOBALS['db_host'] = \$db_host = '$_POST[db_host]';
\$GLOBALS['db_user'] = \$db_user = '$_POST[db_user]';
\$GLOBALS['db_pass'] = \$db_pass = '$_POST[db_pass]';
\$GLOBALS['db_name'] = \$db_name = '$_POST[db_name]';
\$GLOBALS['db_sock'] = '$_POST[db_sock]';
\$GLOBALS['BACKUP_FILEROOT'] = str_replace('admin','_magr',dirname(__FILE__));
\$GLOBALS['BACKUP_WHATSNEW_FILEROOT'] = NULL; // dirname(__FILE__) . '/../../whatsnew/zp/_magr';
\$GLOBALS['CREATE_DAILY_BACKUPS'] = FALSE;
?".">")  /* put dirname inside the ""! */
or die ("Can't create db_connect_params");

	file_put_contents(dirname(__FILE__)."/db_root_params.php", "<?php 
/**
 * @file parameters for configure_mysql.php
 * Automatically generated by $_SERVER[PHP_SELF] at $GLOBALS[current_time]
 */

\$GLOBALS['db_host'] = \$db_host = '$_POST[db_host]';
\$GLOBALS['db_user'] = \$db_user = '$_POST[root_username]';
\$GLOBALS['db_pass'] = \$db_pass = '$_POST[root_password]';
?".">")
or die ("Can't create db_root_params");
}

function create_database_tables() {
	$GLOBALS['BACKUP_MODIFICATION_QUERIES'] = FALSE;

	/* Create all tables before restoring - to use the most up to date definition */
	foreach (array_keys($GLOBALS['ALL_TABLES']) as $table)
		sql_queries_or_die(file_get_contents("$table.sql"));
			# Warning: table_editor_cfg.sql does not exist!

	// restore configuration tables from the general dir:
	$GLOBALS['BACKUP_FILEROOT'] = dirname(__FILE__) . "/../_magr";
	
	print "<h1>Restoring configuration tables</h1>\n";
	foreach (array_keys($GLOBALS['CONFIGURATION_TABLES']) as $table)
		restore_table($table);
}


?>